### ISSUE TITLE
Stack-buffer-overflow in gost12_256

### ISSUE THREAD

**Issue by tankf33der** [rhash/RHash#125]
такой код генерит ошибку

```
#define ARRAY(name, size) \                                                                       
    unsigned char name[size]; \                                                                   
    for(size_t i = 0; i < size; i++) name[i] = i;    

void gost12_256(void) {                                                                           
    struct gost12_ctx ctx;                                                                        
    ARRAY(msg, 128);                                                                              
    unsigned char r[gost12_256_hash_size];                                                        
                                                                                                  
    rhash_gost12_256_init(&ctx);                                                                  
    for (size_t i = 0; i < 128; i++) {                                                            
        rhash_gost12_update(&ctx, msg, i);                                                        
    }                                                                                             
    rhash_gost12_final(&ctx, r);                                                                  
}      
```

```
gost12.c:809:3: runtime error: index 10 out of bounds for type 'uint64_t [8]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior gost12.c:809:3 in 
=================================================================
==439261==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc1c8b9170 at pc 0x5635cc53439e bp 0x7ffc1c8b8e90 sp 0x7ffc1c8b8640
WRITE of size 5 at 0x7ffc1c8b9170 thread T0
    #0 0x5635cc53439d in __asan_memcpy (/home/mpech/rhash-tis/a.out+0x18339d)
    #1 0x5635cc5944e2 in rhash_gost12_update /home/mpech/rhash-tis/gost12.c:809:3
    #2 0x5635cc5eba3a in gost12_256 /home/mpech/rhash-tis/main.c:190:9
    #3 0x5635cc5ef29f in main /home/mpech/rhash-tis/main.c:379:5
    #4 0x7fcacbebe001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #5 0x5635cc4920ed in _start (/home/mpech/rhash-tis/a.out+0xe10ed)

Address 0x7ffc1c8b9170 is located in stack of thread T0 at offset 304 in frame
    #0 0x5635cc5eb72f in gost12_256 /home/mpech/rhash-tis/main.c:183

  This frame has 3 object(s):
    [32, 296) 'ctx' (line 184) <== Memory access at offset 304 overflows this variable
    [368, 496) 'msg' (line 185)
    [528, 560) 'r' (line 186)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/mpech/rhash-tis/a.out+0x18339d) in __asan_memcpy
Shadow bytes around the buggy address:
  0x10000390f1d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000390f1e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000390f1f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000390f200: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 00
  0x10000390f210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10000390f220: 00 00 00 00 00 00 00 00 00 00 00 00 00 f2[f2]f2
  0x10000390f230: f2 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x10000390f240: 00 00 00 00 00 00 f2 f2 f2 f2 00 00 00 00 f3 f3
  0x10000390f250: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000390f260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000390f270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==439261==ABORTING
make: *** [Makefile:2: all] Error 1
```

**Comment by rhash** [comment]
Thank you for reporting this bug!

It affected LibRHash RHASH_GOST12_256 and RHASH_GOST12_512 algorithms. The bug is fixed by commit 775dceb5f887a46f463e7fec09fa146dfb4013d6.
